version: '3.8'

services:
  backend:
    build: .
    container_name: rag-backend
    ports:
      - "8000:8000"
    environment:
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION:-2024-02-15-preview}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME}
      - CHROMA_PERSIST_DIRECTORY=./chroma_db
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./backend:/app/backend
    command: python start_backend.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: .
    container_name: rag-frontend
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://backend:8000
      - STREAMLIT_PORT=8501
    volumes:
      - ./frontend:/app/frontend
    command: python start_frontend.py
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

networks:
  default:
    name: rag-network